version: '2.0'

networks:
  internal:
    driver: bridge

services:
  db:
    image: "${PGIMAGE}"   
    container_name: devbase 
    ports:
      - "${PGPORT}:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
      - "./init:/docker-entrypoint-initdb.d"
    environment:
     POSTGRES_USER:     "${PGUSER}"
     POSTGRES_PASSWORD: "${PGPASSWORD}"
     POSTGRES_DB:       "${PGDATABASE}"
     POSTGRES_MULTIPLE_DATABASES: "devbase"
    networks:
      - internal

  my-app:
    container_name: 'APP'
    restart: always
    image: web-app:latest
    build:
      context: ./
      dockerfile: app.dockerfile
    ports:
      - "5000:80"
    links:
      - "db"
    networks:
      - internal
